# Generated by Django 4.0 on 2022-01-01 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BigFieald',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecandField',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('bigfield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_lessons.bigfieald', verbose_name='BIRINCHI KATEGORIYA')),
            ],
        ),
        migrations.CreateModel(
            name='VideoLessans',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Video', models.FileField(upload_to='images', verbose_name='VIDEO')),
                ('character', models.TextField()),
                ('secondfield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_lessons.secandfield', verbose_name='IKKINCHI KATEGORIYA')),
            ],
        ),
    ]
