# Generated by Django 4.0.4 on 2022-04-26 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video_lessons', '0002_videolessans_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastField',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='NOMI')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[['video', 'video'], ['post', 'post'], ['photo', 'photo'], ['pdf', 'pdf']], max_length=150, verbose_name='TURI')),
                ('File', models.FileField(blank=True, upload_to='images', verbose_name='FILE')),
                ('text', models.TextField(verbose_name='FILE TEKSTI')),
            ],
        ),
        migrations.RenameModel(
            old_name='BigFieald',
            new_name='FirstField',
        ),
        migrations.DeleteModel(
            name='VideoLessans',
        ),
        migrations.AddField(
            model_name='lastfield',
            name='dates',
            field=models.ManyToManyField(related_name='malumot', to='video_lessons.post', verbose_name='Malumotlar'),
        ),
        migrations.AddField(
            model_name='lastfield',
            name='firstfield',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_lessons.firstfield', verbose_name='BIRINCHI KATEGORIYA'),
        ),
        migrations.AddField(
            model_name='lastfield',
            name='secondfield',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='video_lessons.secandfield', verbose_name='IKKINCHI KATEGORIYA'),
        ),
    ]
