# Generated by Django 4.0.4 on 2022-04-25 07:04

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='test',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Savol'),
        ),
    ]
