# Generated by Django 4.0.4 on 2022-04-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0002_alter_tests_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='level',
            field=models.CharField(choices=[['OSON', 'OSON'], ['O`RTA', 'O`RTA'], ['QIYIN', 'QIYIN']], default='OSON', max_length=150, verbose_name='Qiyinlik darajasi'),
        ),
    ]
