# Generated by Django 4.0.4 on 2022-04-25 07:45

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0003_tests_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='test',
            field=django_quill.fields.QuillField(verbose_name='Savol'),
        ),
    ]
