# Generated by Django 4.0.4 on 2022-04-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0004_alter_tests_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='test',
            field=models.TextField(verbose_name='Savol'),
        ),
    ]
